apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: jenkins
  labels:
    app: ha-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha-worker
  template:
    metadata:
      labels:
        app: ha-worker
    spec:
      containers:
      - name: worker-container
        image: ms9019/ha-pipeline-worker:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: redis://redis-service:6379
        - name: RQ_QUEUE
          value: jobs
        command: ["python"]
        args: ["-m","rq","worker","-u","$(REDIS_URL)","$(RQ_QUEUE)"]
